countries = ["usa", "canada", "russia", "china"]
print(countries)
countries.append("mexico")
print(countries)
countries.insert(5, "iraq")
print(countries)
del (countries[2])
print(countries)
poppedcountries = countries.pop(2)
print(poppedcountries)
print(countries)
countries.remove("iraq")
print(countries)
print(sorted(countries))
print(countries)
print(sorted(countries, reverse=True))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
print(len(countries))
del countries[0]
del countries[0]
del countries[0]
print(countries)
